upstream fight_backends {
    least_conn;
    server fightclubservice-b4bye5fxhec7hzhn.mexicocentral-01.azurewebsites.net:443;
    server fightclubservice2-c2g5c0b5gwg2axcs.mexicocentral-01.azurewebsites.net:443;
    server fightclubservice3-hxgndmfegnhjamd0.mexicocentral-01.azurewebsites.net:443;
}

server {
    listen 80;
    server_name fight.santiagosu15.cloud;

    location / {
        proxy_pass https://fight_backends;
        proxy_ssl_server_name on;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}