# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - FightLoadbalancer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2EE4383BEF45473AB40562810A56A6D7 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_7E01421B7BBE46ACBCD67F8FB2C25BE6 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2EE4383BEF45473AB40562810A56A6D7 }}/nginx-balancer:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C7EA08AB210441DB910B37024E4879D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_33894A2CCD704B9C8E7E8FCF908F8D32 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5CCB76DFBA394B5FA99493CCED735CB9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FightLoadbalancer'
          slot-name: 'Production'
          images: 'ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2EE4383BEF45473AB40562810A56A6D7 }}/nginx-balancer:${{ github.sha }}'
          